apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ha.fullname" . }}-env-secret
  labels:
    {{- include "ha.labels" . | nindent 4 }}
data:
{{- if .Values.pgwire.enabled }}
  pg_user: {{ .Values.pgwire.user | b64enc }}
  pg_pass: {{ .Values.pgwire.pass | b64enc }}
{{- end }}
{{- if .Values.nats.enabled }}
  nats_user: {{ .Values.nats.user | default "nats" | b64enc }}
  nats_pass: {{ .Values.nats.pass | default "nats" | b64enc }}
{{- end }}
