apiVersion: v1
kind: Service
metadata:
  name: {{ include "ha.fullname" . }}-headless
  labels:
    app: {{ .Chart.Name }}
    {{- include "ha.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 8080
      protocol: TCP
      name: http
{{- if .Values.nats.enabled}}
    - port: 4222      
      protocol: TCP
      name: nats
    - port: 6222
      protocol: TCP
      name: nats-cluster
{{- end}}{{if .Values.pgwire.enabled}}
    - port: 5432
      protocol: TCP
      name: pg-wire
{{- end}}{{if .Values.mysql.enabled}}
    - port: {{ .Values.mysql.port }}
      protocol: TCP
      name: mysql
{{- end}}
  selector:
    app: {{ .Chart.Name }}
